### ISSUE TITLE
Screen flickers in album view.

### ISSUE THREAD

**Issue by TrebuhD** [VirusThePanda/Aperture-Beta#7]
When viewing a picture inside an album, going back to the album view causes the view to redraw and the screen flickers for a brief moment.

![like this](http://i.giphy.com/kKAwbv3unYEKI.gif)

**Comment by VirusThePanda** [comment]
This is the overlay from the loading icon doing this. Right now, I cannot fix this as it would be way too much backtracking that I do not have time for just yet.
